version: '3'

services:
  diagrams:
    build: ./
    volumes:
      - .:/app/
    expose:
      - ${BACKEND_PORT}
    env_file:
      - .env
    depends_on:
      - diagrams_mongo_db
    networks:
      - crayons

  diagrams_mongo_db:
    image: mongo:4.4.6
    restart: always
    ports:
      - 9003:27017
    env_file:
      - .env
    networks:
      - crayons

networks:
  crayons:
    name: crayons
    driver: bridge
